<a href="https://colab.research.google.com/github/Sivagadiraju/Home_assignment2/blob/main/Task2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

# Create a random 4x4 matrix as input
input_matrix = np.random.rand(4, 4).astype(np.float32)
print("Original Matrix:")
print(input_matrix)

# Reshape the input matrix to match the expected input shape for TensorFlow (batch_size, height, width, channels)
input_matrix = input_matrix.reshape(1, 4, 4, 1)  # Shape: (1, 4, 4, 1)

# Apply 2x2 Max Pooling
max_pool = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2), padding='valid')
max_pooled_matrix = max_pool(input_matrix).numpy().squeeze()
print("\nMax Pooled Matrix:")
print(max_pooled_matrix)

# Apply 2x2 Average Pooling
avg_pool = tf.keras.layers.AveragePooling2D(pool_size=(2, 2), strides=(2, 2), padding='valid')
avg_pooled_matrix = avg_pool(input_matrix).numpy().squeeze()
print("\nAverage Pooled Matrix:")
print(avg_pooled_matrix)

Original Matrix:
[[0.07135898 0.38298896 0.5232169  0.5550122 ]
 [0.2212409  0.6395183  0.32764468 0.26167914]
 [0.14892273 0.09214223 0.15259603 0.27979678]
 [0.11932886 0.27897426 0.23892717 0.77788323]]

Max Pooled Matrix:
[[0.6395183  0.5550122 ]
 [0.27897426 0.77788323]]

Average Pooled Matrix:
[[0.32877678 0.41688827]
 [0.15984201 0.3623008 ]]
